# -*- coding: utf-8 -*-
"""Hello_World_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFMXcO-MPA7JTsHAqKXoVQxxq4zts4iZ
"""



print("Hello, World!")